language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

env:
  - MODE=pytest
  - MODE=autobahn
    SIDE=client
  - MODE=autobahn
    SIDE=server

matrix:
  include:
  - python: 2.7
    env: MODE=pytest WSACCEL=0
  - python: 3.6
    env: MODE=pytest WSACCEL=0
  - os: linux
    language: generic
    env: MODE=pytest PYPY_VERSION=pypy-5.8
  - os: linux
    language: generic
    env: MODE=pytest PYPY_VERSION=pypy3.5-5.8-beta
  - python: 3.6
    env: MODE=docs
  - python: 3.6
    env: MODE=flake8

cache: pip

script:
  - "./.travis/run.sh"
