language: python
sudo: false
python:
  - "3.4"
  - "3.5"
  - "3.6"
sudo: false

env:
  - MODE=pytest
    WSACCEL=1

  - MODE=pytest
    WSACCEL=0

  - MODE=autobahn
    SIDE=client
    WSACCEL=1

  - MODE=autobahn
    SIDE=client
    WSACCEL=0

  - MODE=autobahn
    SIDE=server
    WSACCEL=1

  - MODE=autobahn
    SIDE=server
    WSACCEL=0

matrix:
  include:
  - python: 3.5
    env: MODE=docs
  - python: 3.5
    env: MODE=flake8

script:
  - "./.travis/run.sh"
