language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy-5.3.1"
env:
  - WSACCEL=1
  - WSACCEL=0
install:
  - "pip install -U pip setuptools"
  - "pip install ."
  - "pip install -r test_requirements.txt"
  - "pip install flake8"
  - "pip install sphinx"
  - "pip install codecov"
  - "if [ $WSACCEL -eq 1 ]; then pip install wsaccel; fi"
before_script:
  - "flake8 --max-complexity 10 wsproto"
  - "sphinx-build -nW -b html -d docs/build/doctrees docs/source docs/build/html"
script:
  - "./.travis/run.sh"
