language: python
sudo: false
python:
  - "2.7"
  - "3.5"
  - "3.6"

branches:
  only:
    - master

env:
  - MODE=pytest
    WSACCEL=1

  - MODE=pytest
    WSACCEL=0

  - MODE=autobahn
    SIDE=client
    WSACCEL=1

  - MODE=autobahn
    SIDE=client
    WSACCEL=0

  - MODE=autobahn
    SIDE=server
    WSACCEL=1

  - MODE=autobahn
    SIDE=server
    WSACCEL=0

matrix:
  include:
  - python: 3.6
    env: MODE=docs
  - python: 3.6
    env: MODE=flake8

script:
  - "./.travis/run.sh"
